### ISSUE TITLE
Pkg registration

### ISSUE THREAD

**Issue by zgana** [JuliaAstro/SkyCoords.jl#16]
I am new to julia, and thus necessarily new to SkyCoords and this entire package ecosystem, so I apologize if this is not the right place for this report.  I found `ICRSCoords` and `separation()` here, which seemed to be a perfect fit for some of my julia-noob exercises.  But when I did `Pkg.add("SkyCoords")`, I received a version that was missing `separation()` entirely.  Re-installing via `Pkg.clone(...)` gave me all the goods.  Is it possible to update the registration / cut a release / whatever it takes to get this functionality into the default distribution pipeline?

**Comment by giordano** [comment]
Only @kbarbary can tag a new release, so we should wait for him.

In the meantime, note that with the package manager shipped with latest stable, Julia 0.6, every package is a git repository.  After you install it with `Pkg.add()`, you don't need to clone it again to switch to master, you can just use `Pkg.checkout("SkyCoords")`, which automatically checks out master branch :wink:  However, as far as I understand, this will probably change in Julia 0.7 and may not work anymore

**Comment by kbarbary** [comment]
I just tagged a release, but need to wait for attobot/METADATA.

Should we move this repo to JuliaAstro so you and others can help with things like this, @giordano?

**Comment by giordano** [comment]
Yes, I think it's a good idea to move this to JuliaAstro, to make it also more visible and "official"!

**Comment by kbarbary** [comment]
Sounds good. Let's do that after the release goes through.

**Comment by giordano** [comment]
@kbarbary is attobot enabled on this repository? I can't find its pull request for SkyCoords.  Then, you could move the repository now and open the PR on METADATA later, changing also the URL of the repository

**Comment by kbarbary** [comment]
I thought it was, but now I don't see it. I must have been looking at the wrong repo. I'll remove the release tag and move the repo, add Attobot, and re-release.
